### ISSUE TITLE
Vuziz @ Mrs. Grimm

### ISSUE THREAD

**Issue by buergy** [Thomas-Fritz1/TeamProject#14]
Dear all,

I dropped the Vuzix M100 at Mrs. Grimm's in D16, 4th floor. The one, who picks it up shall please fill in name and e-mail address and sign the form. That's for my records.

Once you picked it up, please let me know by e-mail and close this issue.

Thanks & regards,
Christian Buergy

**Comment by Thomas-Fritz1** [comment]
@franciscoandreso Please close the issue once you wrote the e-mail

**Comment by franciscoandreso** [comment]
I just send the email to confirm it that I picked up the glasses yesterday.

Best Regards,
