### ISSUE TITLE
Project documents

### ISSUE THREAD

**Issue by mcsjuhasz** [Thomas-Fritz1/TeamProject#18]
Hey chaps,

here is a shared link to my google drive to the project document folder, where everybody can upload the required documents:
https://drive.google.com/open?id=0BxrU4sXOpREHZ0E4UnItWl9MQ0k

@neerajaJoshy The requirements doc is there, but it will be surely updated as we are shaping the other documents as well.

Cheers,
Marcell

**Comment by Thomas-Fritz1** [comment]
I've added the file to Github. I think it's better when we stick to one platform. 
See #19
